separate recipies from gremlin and cassandra

diff --git a/templates/default/janusgraph-gremlin.sh.erb b/templates/default/janusgraph-gremlin.sh.erb
--- a/templates/default/janusgraph-gremlin.sh.erb
+++ b/templates/default/janusgraph-gremlin.sh.erb
@@ -12,17 +12,14 @@ abs_path() {
     done
     echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 }
-
 BIN=`abs_path`
 GSRV_CONFIG_TAG=cassandra-es
 : ${CASSANDRA_STARTUP_TIMEOUT_S:=60}
 : ${CASSANDRA_SHUTDOWN_TIMEOUT_S:=60}
-
 : ${GSRV_STARTUP_TIMEOUT_S:=60}
 : ${GSRV_SHUTDOWN_TIMEOUT_S:=60}
 : ${GSRV_IP:=127.0.0.1}
 : ${GSRV_PORT:=8182}
-
 : ${SLEEP_INTERVAL_S:=2}
 VERBOSE=
 COMMAND=
@@ -45,8 +42,30 @@ fi
 
 GREMLIN_FRIENDLY_NAME='Gremlin-Server'
 GREMLIN_CLASS_NAME=org.apache.tinkerpop.gremlin.server.GremlinServer
-CASSANDRA_FRIENDLY_NAME=Cassandra
-CASSANDRA_CLASS_NAME=org.apache.cassandra.service.CassandraDaemon
+
+kill_class() {
+    local p=`$JPS -l | grep "$2" | awk '{print $1}'`
+    if [ -z "$p" ]; then
+        echo "$1 ($2) not found in the java process table"
+        return
+    fi
+    echo "Killing $1 (pid $p)..." >&2
+    case "`uname`" in
+        CYGWIN*) taskkill /F /PID "$p" ;;
+        *)       kill "$p" ;;
+    esac
+}
+
+status_class() {
+    local p=`$JPS -l | grep "$2" | awk '{print $1}'`
+    if [ -n "$p" ]; then
+        echo "$1 ($2) is running with pid $p"
+        return 0
+    else
+        echo "$1 ($2) does not appear in the java process table"
+        return 1
+    fi
+}
 
 wait_for_cassandra() {
     local now_s=`date '+%s'`
@@ -69,7 +88,6 @@ wait_for_cassandra() {
     echo " timeout exceeded ($CASSANDRA_STARTUP_TIMEOUT_S seconds)" >&2
     return 1
 }
-
 
 # wait_for_startup friendly_name host port timeout_s
 wait_for_startup() {
@@ -98,39 +116,9 @@ wait_for_startup() {
     return 1
 }
 
-# wait_for_shutdown friendly_name class_name timeout_s
-wait_for_shutdown() {
-    local friendly_name="$1"
-    local class_name="$2"
-    local timeout_s="$3"
-
-    local now_s=`date '+%s'`
-    local stop_s=$(( $now_s + $timeout_s ))
-
-    while [ $now_s -le $stop_s ]; do
-        status_class "$friendly_name" $class_name >/dev/null
-        if [ $? -eq 1 ]; then
-            # Class not found in the jps output.  Assume that it stopped.
-            return 0
-        fi
-        sleep $SLEEP_INTERVAL_S
-        now_s=`date '+%s'`
-    done
-
-    echo "$friendly_name shutdown timeout exceeded ($timeout_s seconds)" >&2
-    return 1
-}
-
 start() {
-    status_class $CASSANDRA_FRIENDLY_NAME $CASSANDRA_CLASS_NAME >/dev/null && status && echo "Stop services before starting" && exit 1
-    echo "Forking Cassandra..."
-    if [ -n "$VERBOSE" ]; then
-        CASSANDRA_INCLUDE="$BIN"/cassandra.in.sh "$BIN"/cassandra || exit 1
-    else
-        CASSANDRA_INCLUDE="$BIN"/cassandra.in.sh "$BIN"/cassandra >/dev/null 2>&1 || exit 1
-    fi
     wait_for_cassandra || {
-        echo "See $BIN/../log/cassandra.log for Cassandra log output."    >&2
+        echo "See cassandra.log for Cassandra log output."    >&2
         return 1
     }
 
@@ -142,7 +130,7 @@ start() {
         "$BIN"/gremlin-server.sh conf/gremlin-server/gremlin-server.yaml >/dev/null 2>&1 &
     fi
     wait_for_startup 'Gremlin-Server' $GSRV_IP $GSRV_PORT $GSRV_STARTUP_TIMEOUT_S || {
-        echo "See $BIN/../log/gremlin-server.log for Gremlin-Server log output."  >&2
+        echo "See gremlin-server.log for Gremlin-Server log output."  >&2
         return 1
     }
     disown
@@ -153,70 +141,14 @@ start() {
 stop() {
     kill_class        $GREMLIN_FRIENDLY_NAME $GREMLIN_CLASS_NAME
     wait_for_shutdown $GREMLIN_FRIENDLY_NAME $GREMLIN_CLASS_NAME $GSRV_SHUTDOWN_TIMEOUT_S
-    kill_class        $CASSANDRA_FRIENDLY_NAME $CASSANDRA_CLASS_NAME
-    wait_for_shutdown $CASSANDRA_FRIENDLY_NAME $CASSANDRA_CLASS_NAME $CASSANDRA_SHUTDOWN_TIMEOUT_S
-}
-
-kill_class() {
-    local p=`$JPS -l | grep "$2" | awk '{print $1}'`
-    if [ -z "$p" ]; then
-        echo "$1 ($2) not found in the java process table"
-        return
-    fi
-    echo "Killing $1 (pid $p)..." >&2
-    case "`uname`" in
-        CYGWIN*) taskkill /F /PID "$p" ;;
-        *)       kill "$p" ;;
-    esac
-}
-
-status_class() {
-    local p=`$JPS -l | grep "$2" | awk '{print $1}'`
-    if [ -n "$p" ]; then
-        echo "$1 ($2) is running with pid $p"
-        return 0
-    else
-        echo "$1 ($2) does not appear in the java process table"
-        return 1
-    fi
 }
 
 status() {
     status_class $GREMLIN_FRIENDLY_NAME $GREMLIN_CLASS_NAME
-    status_class $CASSANDRA_FRIENDLY_NAME $CASSANDRA_CLASS_NAME
-}
-
-clean() {
-    echo -n "Are you sure you want to delete all stored data and logs? [y/N] " >&2
-    read response
-    if [ "$response" != "y" -a "$response" != "Y" ]; then
-        echo "Response \"$response\" did not equal \"y\" or \"Y\".  Canceling clean operation." >&2
-        return 0
-    fi
-
-    if cd "$BIN"/../db 2>/dev/null; then
-        rm -rf cassandra es
-        echo "Deleted data in `pwd`" >&2
-        cd - >/dev/null
-    else
-        echo 'Data directory does not exist.' >&2
-    fi
-
-    if cd "$BIN"/../log; then
-        rm -f cassandra*.log
-        rm -f elasticsearch*.log
-        rm -f gremlin-server.log
-        echo "Deleted logs in `pwd`" >&2
-        cd - >/dev/null
-    fi
 }
 
 usage() {
-    echo "Usage: $0 [options] {start|stop|status|clean}" >&2
-    echo " start:  fork Cassandra, ES, and Gremlin-Server processes" >&2
-    echo " stop:   kill running Cassandra, ES, and Gremlin-Server processes" >&2
-    echo " status: print Cassandra, ES, and Gremlin-Server process status" >&2
-    echo " clean:  permanently delete all graph data (run when stopped)" >&2
+    echo "Usage: $0 [options] {start|stop|status}" >&2
     echo "Options:" >&2
     echo " -v      enable logging to console in addition to logfiles" >&2
 }
